version: "3.7"

networks:
  modelx:

services:
  modelxd:
    image: kubegems/modelx:latest
    restart: always
    ports:
      - "8080:8080"
    command:
      - --s3-url=http://__ADVERTISED_IP__:9000
      - --s3-access-key=EofgzWDUh6
      - --s3-secret-key=iVPDZCN4rVpxQB1Skp6foQMWOV8IHVM4
      - --s3-bucket=modelx
      - --enable-redirect=true
      - --listen=:8080
    networks:
      - modelx
    depends_on:
    - minio
  minio:
    image: minio/minio:RELEASE.2020-09-21T22-31-59Z
    volumes:
      - 'minio_data:/data'
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=EofgzWDUh6
      - MINIO_SECRET_KEY=iVPDZCN4rVpxQB1Skp6foQMWOV8IHVM4
    command: server  /data
    networks:
      - modelx
    depends_on:
    - minio-init
  minio-init:
    image: busybox:latest
    command: mkdir -p /data/modelx
    networks:
      - modelx
    volumes:
      - 'minio_data:/data:rw'
volumes:
  minio_data:
    driver: local