# syntax=docker/dockerfile:1
FROM alpine
# TARGETOS TARGETARCH already set by '--platform'
ARG TARGETOS TARGETARCH 
COPY modelxdl-${TARGETOS}-${TARGETARCH} /app/modelxdl
WORKDIR /app
ENTRYPOINT ["/app/modelxdl"]
